server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springstudy?serverTimezone=GMT%2b8
    username: root
    password: abc.123456
  application:
    name: study_spring
mybatis:
  mapper-locations: classpath:mapper/*.xml
